### ISSUE TITLE
I would like to add and view all my booked trips

### ISSUE THREAD

**Issue by clovellbsc** [adamwoodcock98/travel-angel#44]
As a user,
So that I can see what trips I have made,
I would like to add and view all my booked trips

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Trips page](https://trello.com/c/sU61tAMP/66-trips-page)

**Comment by heykathl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement a 'Yours trip' page](https://trello.com/c/tz3myyjV/65-implement-a-yours-trip-page)
