### ISSUE TITLE
I would like to add details for my booked flight 

### ISSUE THREAD

**Issue by adamwoodcock98** [adamwoodcock98/travel-angel#5]
As a user,
So that I don’t miss my flight
I would like to add details for my booked flight (flight number, time, gate, airport)

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to upload information on my booked flight details](https://trello.com/c/CTEnXHgP/22-i-would-like-to-upload-information-on-my-booked-flight-details)

**Comment by heykathl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to add details for my booked flight (add flight modal)](https://trello.com/c/Me0P3461/48-i-would-like-to-add-details-for-my-booked-flight-add-flight-modal)

**Comment by adamwoodcock98** [comment]
[Done](https://github.com/adamwoodcock98/travel-angel/pull/34/files).
