### ISSUE TITLE
I would like to add details for my booked accommodation 

### ISSUE THREAD

**Issue by adamwoodcock98** [adamwoodcock98/travel-angel#6]
As a user,
So that I know where I’ll be staying when I travel
I would like to add details for my booked accommodation

**Comment by adamwoodcock98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to upload information on my booked accommodation](https://trello.com/c/6njbj8zC/23-i-would-like-to-upload-information-on-my-booked-accommodation)

**Comment by clovellbsc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I would like to add details for my booked accommodation (modal)](https://trello.com/c/6njbj8zC/23-i-would-like-to-add-details-for-my-booked-accommodation-modal)

**Comment by adamwoodcock98** [comment]
[Done](https://github.com/adamwoodcock98/travel-angel/pull/37).
